spring.application.name=project1

# ===================================================================
# 1. DATABASE CONNECTION (DATASOURCE)
# ===================================================================
spring.datasource.url=jdbc:mysql://hayabusa.proxy.rlwy.net:30903/railway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=OjnOmHwgpmDaTccjkJFqcSmiDpuUBLvK
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================================
# 2. JPA & HIBERNATE CONFIGURATION
# ===================================================================
# Database initialization strategy: none, validate, update, create, create-drop
spring.jpa.hibernate.ddl-auto=update

# Disable Open Session In View for cleaner service/controller boundaries.
spring.jpa.open-in-view=false

# ===================================================================
# 3. DEBUGGING & LOGGING
# ===================================================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# 4. REDIS
# ===================================================================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.repositories.enabled=false

# ===================================================================
# 5. SERVER & ACTUATOR
# ===================================================================
server.port=8081
management.endpoints.web.exposure.include=health,info,metrics,prometheus


razorpay.key.id=rzp_test_TBLCwpTB9Xemeh
razorpay.key.secret=4bSqDYVdQQLnOGFL5nPyXQcw

