spring.application.name=project1

# ===================================================================
# 1. DATABASE CONNECTION (DATASOURCE)
# ===================================================================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_ROOT}
spring.datasource.password=${DATABASE_Password}
spring.datasource.driver-class-name=${DATABASE_NAME}

# ===================================================================
# 2. JPA & HIBERNATE CONFIGURATION
# ===================================================================
# Database initialization strategy: none, validate, update, create, create-drop
spring.jpa.hibernate.ddl-auto=update

# Disable Open Session In View for cleaner service/controller boundaries.
spring.jpa.open-in-view=false

# ===================================================================
# 3. DEBUGGING & LOGGING
# ===================================================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# 4. REDIS
# ===================================================================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${Redis_Port}
spring.data.redis.repositories.enabled=${redis_repositories}

# ===================================================================
# 5. SERVER & ACTUATOR
# ===================================================================
server.port=${SERVER_PORT}
management.endpoints.web.exposure.include=health,info,metrics,prometheus


razorpay.key.id=${RAZORPAY_ID}
razorpay.key.secret=${RAZORPAY_KEY}

# ===================================================================
# 6. JWT SECURITY
# ===================================================================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}


